import { existsSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { defineConfig } from 'vitepress'
import { withMermaid } from 'vitepress-plugin-mermaid'

// generated by `bun run docs:api` (typedoc); absent until that has run
const apiSidebarFile = fileURLToPath(new URL('../en/api/typedoc-sidebar.json', import.meta.url))
const apiSidebar = existsSync(apiSidebarFile) ? JSON.parse(readFileSync(apiSidebarFile, 'utf8')) : []

export default withMermaid(defineConfig({
  title: '@alt-point/active-models',
  description: 'Reactive DTO models with Proxy and more useful classes, decorators, and hooks',
  base: '/active-models/',
  cleanUrls: true,
  themeConfig: {
    // shared across all locales
    socialLinks: [
      { icon: 'github', link: 'https://github.com/alt-point/active-models' },
      { icon: 'npm', link: 'https://www.npmjs.com/package/@alt-point/active-models' },
    ],
    search: {
      provider: 'local',
    },
  },
  locales: {
    root: {
      label: 'Русский',
      lang: 'ru',
      link: '/',
      themeConfig: {
        nav: [
          { text: 'Главная', link: '/' },
          { text: 'Пример с decorators', link: '/active-model-with-decorators' },
          { text: 'Жизненный цикл', link: '/model-lifecycle' },
          { text: 'v4.0.0', link: 'https://github.com/alt-point/active-models/blob/master/CHANGELOG.md' },
          { text: 'GitHub', link: 'https://github.com/alt-point/active-models' },
        ],
        sidebar: [
          {
            text: 'Руководство',
            items: [
              { text: 'Пример с decorators', link: '/active-model-with-decorators' },
              { text: 'Справочник опций @ActiveField()', link: '/active-field-options' },
              { text: 'Жизненный цикл модели', link: '/model-lifecycle' },
              { text: 'Продвинутые возможности', link: '/active-model-advanced' },
              { text: 'Пример для Node.js-сервера', link: '/node-example' },
            ],
          },
          {
            text: 'Статьи',
            items: [
              { text: 'Отслеживание изменений: isTouched()', link: '/dirty-tracking' },
              { text: 'Трансформация моделей: mapTo()', link: '/mapping' },
              { text: 'ActiveCollection: типизированный массив', link: '/collections' },
              { text: 'Валидация, нормализация, переходы', link: '/validation' },
              { text: 'Инварианты, транзакции, undo', link: '/integrity' },
            ],
          },
          {
            text: 'Справка',
            items: [
              { text: 'Известные ограничения', link: '/limitations' },
              { text: 'Миграция на 4.0', link: '/migration' },
              { text: 'Тестирование и качество', link: '/testing' },
              { text: 'Для AI-агентов', link: '/agents' },
            ],
          },
        ],
        outline: {
          label: 'На этой странице',
        },
        docFooter: {
          prev: 'Предыдущая страница',
          next: 'Следующая страница',
        },
        darkModeSwitchLabel: 'Тема',
        returnToTopLabel: 'Наверх',
      },
    },
    en: {
      label: 'English',
      lang: 'en',
      link: '/en/',
      themeConfig: {
        nav: [
          { text: 'Home', link: '/en/' },
          { text: 'Decorators example', link: '/en/active-model-with-decorators' },
          { text: 'Lifecycle', link: '/en/model-lifecycle' },
          { text: 'v4.0.0', link: 'https://github.com/alt-point/active-models/blob/master/CHANGELOG.md' },
          { text: 'GitHub', link: 'https://github.com/alt-point/active-models' },
        ],
        sidebar: [
          {
            text: 'Guide',
            items: [
              { text: 'Decorators example', link: '/en/active-model-with-decorators' },
              { text: '@ActiveField() options reference', link: '/en/active-field-options' },
              { text: 'Model lifecycle', link: '/en/model-lifecycle' },
              { text: 'Advanced features', link: '/en/active-model-advanced' },
              { text: 'Node.js server example', link: '/en/node-example' },
            ],
          },
          {
            text: 'Articles',
            items: [
              { text: 'Change tracking: isTouched()', link: '/en/dirty-tracking' },
              { text: 'Model mapping: mapTo()', link: '/en/mapping' },
              { text: 'ActiveCollection: a typed array', link: '/en/collections' },
              { text: 'Validation, normalization, transitions', link: '/en/validation' },
              { text: 'Invariants, transactions, undo', link: '/en/integrity' },
            ],
          },
          {
            text: 'Reference',
            items: [
              { text: 'Known limitations', link: '/en/limitations' },
              { text: 'Migrating to 4.0', link: '/en/migration' },
              { text: 'Testing and quality', link: '/en/testing' },
              { text: 'For AI agents', link: '/en/agents' },
            ],
          },
          ...(apiSidebar.length ? [{ text: 'API reference', link: '/en/api/', items: apiSidebar }] : []),
        ],
      },
    },
  },
}))
